### ISSUE TITLE
Unable to use Chrome debugging tool

### ISSUE THREAD

**Issue by c-bush** [OP-Engineering/op-sqlcipher#10]
**Describe the bug**
When a breakpoint is hit, this error occurs.  Is there a way to enable Chrome Debugging tools when importing this library?

**Versions:**
 - OS and version: simulator iOS 16.4
 - op-sqlite version: [Have you tried the latest version?]
 - RN version: 2.0.13

![image](https://github.com/OP-Engineering/op-sqlcipher/assets/66798338/19d82041-9f96-4cda-b5d0-2a803485ef9a)

**Comment by ospfranco** [comment]
You cannot use chrome debugger with JSI libraries. Nothing can be done about this.

**Comment by c-bush** [comment]
thank you for confirming!
