### ISSUE TITLE
Could not find or use auto-linked framework 'OpenSSL'

### ISSUE THREAD

**Issue by hongyingyang78** [OP-Engineering/op-sqlcipher#11]
The project runs without any problems, but when you package it, you Could not find or use auto-linked framework 'OpenSSL'. In order to solve the packing problem, I had to work on the project in General->Frameworks, Libraries, and Embedded in the Content added the Pods/OpenSSL - Universal/OpenSSL. The framework can be packaged, but running and must be removed, what is the lack of allocation of cause?

<img width="701" alt="截屏2024-01-31 12 32 22" src="https://github.com/OP-Engineering/op-sqlcipher/assets/143774358/be0a70db-095d-4f7d-a68f-57385ce9e726">

![20240131-124156](https://github.com/OP-Engineering/op-sqlcipher/assets/143774358/e0803c80-5497-4d19-b99b-a55e509206cf)

**Comment by ospfranco** [comment]
There is something wrong with your project cocoapods. Nothing wrong with the library.

**Comment by hongyingyang78** [comment]
> 你的项目cocoapods有问题。图书馆没有什么问题。

I changed to a new computer, never used the computer, installed the development environment from scratch, integrated the project, still packaging and reporting this error, so, I don't think it is my problem. There is something wrong with both computers
