### ISSUE TITLE
No such module: fts5

### ISSUE THREAD

**Issue by davidivkovic** [OP-Engineering/op-sqlcipher#12]
Just a quick question.

I have a FTS5 table that I am trying to query and I've enabled the extension by adding the `post_install` block to my `<PROJECT_ROOT>/iOS/Podfile` containing `config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SQLITE_ENABLE_FTS5=1'` with `target.name == "op-sqlcipher"`

I've cleaned and recompiled everything multiple times but still get the error `[Error: Exception in HostFunction: [op-sqlite] SQL statement error:1 description:no such module: fts5. See error codes: https://www.sqlite.org/rescode.html]`

Reading the database using the encryption key and querying other tables that don't use this extension works fine. I am also using Expo but that shouldn't be the problem since the library works perfectly except for fts5.

Is there anything else that needs to be done? I am a bit lost here. Thanks!

Edit: Seems to work fine on Android, only issue is on iOS.

**Comment by ospfranco** [comment]
You need to do a clean compilation maybe?

**Comment by davidivkovic** [comment]
I ended up deleting the whole `ios` folder and reconfigured my whole xcode project from scratch which somehow ended up solving the problem. Thank you a lot! 

Closing this issue.
