### ISSUE TITLE
File is not a database

### ISSUE THREAD

**Issue by shiroze** [OP-Engineering/op-sqlcipher#3]
![image](https://github.com/OP-Engineering/op-sqlcipher/assets/6022114/6b5bfe03-d265-4f91-95ee-80b9b8e33a13)

File is not a database when open database with encryption. I'm using remote db download the sqlite file then copy paste into data/package/databases using react-native-fs

I'm using DB Browser for SQLite for encryption.
`Page size 1024 SQLCipher 3 defaults`
sample code :

```
import { open } from '@op-engineering/op-sqlcipher';

export let db = open({
  name: "mydb.db",
  location: '../databases',
  encryptionKey: "mydbpw"
});

export const SelectQuery = async (query, params = []) => {
  db.execute(query, params).then((result) => {
    reactotron.log(result);
  }).catch((error) => {
    reactotron.log(error);
  });
};
```

Package Version:

> "react": "18.2.0",
> "react-native": "0.72.6",
> "@op-engineering/op-sqlcipher": "^1.0.8",

**Comment by ospfranco** [comment]
Are you sure your db is a sqlcipher valid db? Usually that's the message I get when opening a non encrypted db.

Other possible causes are the compilation flags for SQLChiper are different?

**Comment by shiroze** [comment]
Step to produce current DB:
1. Open DBBrowser for SQLCipher
2. Create New DB, Add Table insert some data
3. Set Encryption from menu Tools > Set Encryption
4. Select SQLCipher 3 Default / 4 Default then Save
![image](https://github.com/OP-Engineering/op-sqlcipher/assets/6022114/1a8dd3e2-f655-47fe-9c02-aabf90de4055)

DB Browser Support SQLCipher from [here](https://github.com/sqlcipher/sqlcipher) and [here](https://www.zetetic.net/sqlcipher/)

**Comment by ospfranco** [comment]
I have no idea how DB Browser encrypts the db. You will have to figure out that one yourself.

On op-sqlite the passphrase is passed via [a pragma SQL query](https://github.com/OP-Engineering/op-sqlcipher/blob/main/cpp/bridge.cpp#L99). Maybe DB Browser is passing the passphrase as a raw binary.

**Comment by ospfranco** [comment]
[SQLCipher has some configuration that might be causing the issue](https://github.com/sqlcipher/sqlcipher#encrypting-a-database). I will keep this open for now in case somebody faces the same issue in the future and finds a solution.

**Comment by ospfranco** [comment]
It seems the latest version published had a missing podspec file. Can you try with the latest version @shiroze ?

**Comment by shiroze** [comment]
> It seems the latest version published had a missing podspec file. Can you try with the latest version @shiroze ?

![image](https://github.com/OP-Engineering/op-sqlcipher/assets/6022114/1da56aa2-e92e-4696-9890-2966103f7d6c)

When using latest version this keep showing even remove caches etc

**Comment by ospfranco** [comment]
Ah yeah, if you have multiple projects that import OpenSSL then it will clash. I will add it to the repo now.

Glad it is working now!

**Comment by ospfranco** [comment]
Hmmm actually now that I think about it, if you don't have any library that generates `libcrypto.so` then it won't be included in the build and the database will not be encrypted... I will have to ask somebody more versed in gradle how to solve this

**Comment by ospfranco** [comment]
Created a new release that should solve the conflicts for now

https://github.com/OP-Engineering/op-sqlcipher/releases/tag/1.0.16

It's still up to see if it will generate more conflicts with other libraries that depend on openssl

**Comment by Nodonisko** [comment]
@ospfranco I will try to integrate this lib into our big app this week so I will let you know if that works.

**Comment by ospfranco** [comment]
Please create another issue if you find any libcrypto.so conflicts
