### ISSUE TITLE
`inMemory: true` option is gone on `open` after upgrading to 2.0.0

### ISSUE THREAD

**Issue by nikgraf** [OP-Engineering/op-sqlcipher#6]
<img width="459" alt="Screenshot 2023-12-05 at 08 27 47" src="https://github.com/OP-Engineering/op-sqlcipher/assets/223045/2e7730dd-b664-4af2-8a79-0ec6897c8dce">

**Comment by ospfranco** [comment]
2.0.0 was a breaking change, the release notes mention it. [The new usage is on the README](https://github.com/OP-Engineering/op-sqlcipher#in-memory).

**Comment by ospfranco** [comment]
Ah oops, botched merge on the README, give me a minute.

You should now pass:

```
open({
name: 'foo',
location: ':memory:'
})
```

**Comment by nikgraf** [comment]
thanks 🙇
