### ISSUE TITLE
iOS: build error: conflict with expo updates package. "Redefinition of 'sqlite3_'..."

### ISSUE THREAD

**Issue by vince-roy** [OP-Engineering/op-sqlcipher#8]
**Describe the bug**
When running alongside the [expo-updates](https://www.npmjs.com/package/expo-updates) package, the build fails on iOS. 

When running with `OP_SQLITE_USE_PHONE_VERSION=1`, the build succeeds but the database no longer opens and instead throws a `file is not a database error`.

Running `expo run:ios --no-build-cache --configuration Release` in the following repository (after installing node modules) 
https://github.com/vince-roy/op-sqlcipher-android results in the following build errors:

```
❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:728:8)

  726 | */
  727 | typedef struct sqlite3_file sqlite3_file;
> 728 | struct sqlite3_file {
      |        ^ redefinition of 'sqlite3_file'
  729 |   const struct sqlite3_io_methods *pMethods; /* Methods for an open file */
  730 | };
  731 | 


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:834:8)

  832 | */
  833 | typedef struct sqlite3_io_methods sqlite3_io_methods;
> 834 | struct sqlite3_io_methods {
      |        ^ redefinition of 'sqlite3_io_methods'
  835 |   int iVersion;
  836 |   int (*xClose)(sqlite3_file *);
  837 |   int (*xRead)(sqlite3_file *, void *, int iAmt, sqlite3_int64 iOfst);


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:1463:8)

  1461 | typedef struct sqlite3_vfs sqlite3_vfs;
  1462 | typedef void (*sqlite3_syscall_ptr)(void);
> 1463 | struct sqlite3_vfs {
       |        ^ redefinition of 'sqlite3_vfs'
  1464 |   int iVersion;       /* Structure version number (currently 3) */
  1465 |   int szOsFile;       /* Size of subclassed sqlite3_file */
  1466 |   int mxPathname;     /* Maximum file pathname length */


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:1763:8)

  1761 | */
  1762 | typedef struct sqlite3_mem_methods sqlite3_mem_methods;
> 1763 | struct sqlite3_mem_methods {
       |        ^ redefinition of 'sqlite3_mem_methods'
  1764 |   void *(*xMalloc)(int);          /* Memory allocation function */
  1765 |   void (*xFree)(void *);          /* Free a prior allocation */
  1766 |   void *(*xRealloc)(void *, int); /* Resize an allocation */


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:3918:29)

  3916 | ** invoked prior to calling sqlite3_free_filename(Y).
  3917 | */
> 3918 | SQLITE_API sqlite3_filename sqlite3_create_filename(const char *zDatabase,
       |                             ^ conflicting types for 'sqlite3_create_filename'
  3919 |                                                     const char *zJournal,
  3920 |                                                     const char *zWal,
  3921 |                                                     int nParam,


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:3923:17)

  3921 |                                                     int nParam,
  3922 |                                                     const char **azParam);
> 3923 | SQLITE_API void sqlite3_free_filename(sqlite3_filename);
       |                 ^ conflicting types for 'sqlite3_free_filename'
  3924 | 
  3925 | /*
  3926 | ** CAPI3REF: Error Codes And Messages


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:7165:8)

  7163 | ** any database connection.
  7164 | */
> 7165 | struct sqlite3_module {
       |        ^ redefinition of 'sqlite3_module'
  7166 |   int iVersion;
  7167 |   int (*xCreate)(sqlite3 *, void *pAux, int argc, const char *const *argv,
  7168 |                  sqlite3_vtab **ppVTab, char **);


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:7304:8)

  7302 | ** 3009000.
  7303 | */
> 7304 | struct sqlite3_index_info {
       |        ^ redefinition of 'sqlite3_index_info'
  7305 |   /* Inputs */
  7306 |   int nConstraint; /* Number of entries in aConstraint */
  7307 |   struct sqlite3_index_constraint {


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:7307:10)

  7305 |   /* Inputs */
  7306 |   int nConstraint; /* Number of entries in aConstraint */
> 7307 |   struct sqlite3_index_constraint {
       |          ^ redefinition of 'sqlite3_index_constraint'
  7308 |     int iColumn;          /* Column constrained.  -1 for ROWID */
  7309 |     unsigned char op;     /* Constraint operator */
  7310 |     unsigned char usable; /* True if this constraint is usable */


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:7314:10)

  7312 |   } * aConstraint;        /* Table of WHERE clause constraints */
  7313 |   int nOrderBy;           /* Number of terms in the ORDER BY clause */
> 7314 |   struct sqlite3_index_orderby {
       |          ^ redefinition of 'sqlite3_index_orderby'
  7315 |     int iColumn;        /* Column number */
  7316 |     unsigned char desc; /* True for DESC.  False for ASC. */
  7317 |   } * aOrderBy;         /* The ORDER BY clause */


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:7319:10)

  7317 |   } * aOrderBy;         /* The ORDER BY clause */
  7318 |   /* Outputs */
> 7319 |   struct sqlite3_index_constraint_usage {
       |          ^ redefinition of 'sqlite3_index_constraint_usage'
  7320 |     int argvIndex;      /* if >0, constraint is part of argv to xFilter */
  7321 |     unsigned char omit; /* Do not code a test for this constraint */
  7322 |   } * aConstraintUsage;


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:7482:8)

  7480 | ** freed by sqlite3_free() and the zErrMsg field will be zeroed.
  7481 | */
> 7482 | struct sqlite3_vtab {
       |        ^ redefinition of 'sqlite3_vtab'
  7483 |   const sqlite3_module *pModule; /* The module for this virtual table */
  7484 |   int nRef;                      /* Number of open cursors */
  7485 |   char *zErrMsg;                 /* Error message from sqlite3_mprintf() */


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:7506:8)

  7504 | ** are common to all implementations.
  7505 | */
> 7506 | struct sqlite3_vtab_cursor {
       |        ^ redefinition of 'sqlite3_vtab_cursor'
  7507 |   sqlite3_vtab *pVtab; /* Virtual table of this cursor */
  7508 |   /* Virtual table implementations will typically add additional fields */
  7509 | };


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:7997:8)

  7995 | */
  7996 | typedef struct sqlite3_mutex_methods sqlite3_mutex_methods;
> 7997 | struct sqlite3_mutex_methods {
       |        ^ redefinition of 'sqlite3_mutex_methods'
  7998 |   int (*xMutexInit)(void);
  7999 |   int (*xMutexEnd)(void);
  8000 |   sqlite3_mutex *(*xMutexAlloc)(int);


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:8763:8)

  8761 | */
  8762 | typedef struct sqlite3_pcache_page sqlite3_pcache_page;
> 8763 | struct sqlite3_pcache_page {
       |        ^ redefinition of 'sqlite3_pcache_page'
  8764 |   void *pBuf;   /* The content of the page */
  8765 |   void *pExtra; /* Extra information associated with the page */
  8766 | };


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:8928:8)

  8926 | */
  8927 | typedef struct sqlite3_pcache_methods2 sqlite3_pcache_methods2;
> 8928 | struct sqlite3_pcache_methods2 {
       |        ^ redefinition of 'sqlite3_pcache_methods2'
  8929 |   int iVersion;
  8930 |   void *pArg;
  8931 |   int (*xInit)(void *);


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:8952:8)

  8950 | */
  8951 | typedef struct sqlite3_pcache_methods sqlite3_pcache_methods;
> 8952 | struct sqlite3_pcache_methods {
       |        ^ redefinition of 'sqlite3_pcache_methods'
  8953 |   void *pArg;
  8954 |   int (*xInit)(void *);
  8955 |   void (*xShutdown)(void *);


❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:10324:16)

  10322 | ** the most recent version.
  10323 | */
> 10324 | typedef struct sqlite3_snapshot {
        |                ^ redefinition of 'sqlite3_snapshot'
  10325 |   unsigned char hidden[48];
  10326 | } sqlite3_snapshot;
  10327 | 
```

**Versions:**
 - iOS 16, Mac Ventura
 -   @op-engineering/op-sqlcipher": "^2.0.8"
 - RN version: 0.73

**Reproducible example**
https://github.com/vince-roy/op-sqlcipher-android 
1. Run `npm install`
2. Run `npx expo run:ios --no-build-cache --configuration Release`

**Comment by ospfranco** [comment]
You cannot use the OS version with sqlcipher, sqlcipher is a fork of sqlite. I will update the README.

I guess expo updates is using sqlite to store and keep track of the updates, unfortunately that means you won't be able to both as both export the same symbols.

You should ask them if there is anything that can be done or why does expo-update depends on sqlite

**Comment by vince-roy** [comment]
Looks like they use their own version of sqlite3 to store a log of over the air updates on the device. 
https://github.com/expo/expo/blob/bf526ca325cd8073e00f6014f07f07450e7b6576/packages/expo-updates/ios/EXUpdates.podspec#L24

I don't think they're going to change that anytime soon. 

Thanks for chiming in, @ospfranco. I think you can close the issue as it's not really a problem with `op-sqlcipher` specifically.

**Comment by ospfranco** [comment]
well, you can patch-package (or yarn patch) the podspec yourself and comment out the dependency on `sqlite3`, maybe it will compile. I don't know if there is any other way to exclude sources on iOS, at least for android pickFirst is possible and then expo should use sqlcipher instead of raw sqlite, if the order is correct.

**Comment by vince-roy** [comment]
I tried the patch, but I get:
```
❌  (node_modules/expo-updates/ios/EXUpdates/Database/UpdatesDatabase.swift:13:8)

  11 | 
  12 | import Foundation
> 13 | import sqlite3
     |        ^ no such module 'sqlite3'
  14 | import EXManifests
  15 | 
  16 | internal enum UpdatesDatabaseError: Error {
  ```

**Comment by louismullie** [comment]
Thanks for your attention on this issue @ospfranco - it's pretty critical for us. Where can we find the link to sponsor your work?

**Comment by ospfranco** [comment]
Hmm the sponsor link is [here](https://github.com/sponsors/ospfranco)... I'm not sure if it is fixable though, I guess I could spend some hours seeing if I can namespace the symbols, that might prevent a collision, but there is no guarantee it will work

**Comment by ospfranco** [comment]
The sqlcipher docs have this:

```
Please note that we DO NOT SUPPORT using SQLCipher with a project that includes a separate sqlite3 dependency, including via CocoaPods. That sort of configuration carries multiple inherent risks, including undefined behavior, deadlocks, loss of data, loss of encryption functionality, etc.
```

[More info here](https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688), the use case of op-sqlcipher is not included do, since it builds the library from source.

**Comment by ospfranco** [comment]
I just tried deleting the `sqlite3.h` from the sources of `op-sqlcipher` and the app compiles, but I don't know if it will work (meaning if sqlcipher symbols are picked or pure sqlite3 symbols). Can you guys give it a try in your project and see if your db is still working?

**Comment by ospfranco** [comment]
Ok, I think I got the namespace working, you need to add an opening namespace `namespace opsqlite {` at line 45 and a closing `}` at 10643. Then the app is compiled. You can give it a try or I can send you a patch-package tomorrow that will automate this.

**Comment by louismullie** [comment]
Sure thing, will do and thanks for building such great software @ospfranco

**Comment by ospfranco** [comment]
I forgot C doesn't have namespaces, so that solution won't work.

I just tried the [sample op-sqlcipher-android](https://github.com/vince-roy/op-sqlcipher-android) and it is compiling fine for me on iOS. I don't see sqlite3 as a dependency on the ExpoUpdates package:

![Oscar Franco Screen 000698](https://github.com/OP-Engineering/op-sqlcipher/assets/1634213/f159acef-fec3-4263-9e59-a698257d0a97)

So, in any case, here is something that *might* work. You can patch package both op-sqlcipher and ExpoUpdates. On op-sqlcipher remove the sources (sqlite3.c and sqlite3.h) and add SQLCipher as pod (https://cocoapods.org/pods/SQLCipher). On ExpoUpdates, replace the dependency on `sqlite3` with the same sqlcipher pod, maybe then cocoapods will be smart enough to only require it once. Once that is done, on the ExpoUpdate swift sources replace the import of sqlite3 with sqlcipher and it might work.

**Comment by vince-roy** [comment]
@ospfranco they are adding `sqlite3` as a dependency in the next version of their package https://github.com/expo/expo/blob/2a96b86e780a2cc6c4cf4d5b38849f108f0517b0/packages/expo-updates/ios/EXUpdates.podspec#L24. 

If I clone https://github.com/vince-roy/op-sqlcipher-android (which has the version of `expo-updates` without the explicit `sqlite3` dependency), then run `npm i` followed by `npx expo run:ios --no-build-cache --configuration Release`, I'm still getting build errors related to redefinition of sqlite3:

```
❌  (ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h:10326:3)

  10324 | typedef struct sqlite3_snapshot {
  10325 |   unsigned char hidden[48];
> 10326 | } sqlite3_snapshot;
        |   ^ typedef redefinition with different types ' vs 'struct sqlite3_snapshot')
  10327 | 
  10328 | /*
  10329 | ** CAPI3REF: Record A Database Snapshot
```

**Comment by vince-roy** [comment]
Trying this now:

> So, in any case, here is something that might work. You can patch package both op-sqlcipher and ExpoUpdates. On op-sqlcipher remove the sources (sqlite3.c and sqlite3.h) and add SQLCipher as pod (https://cocoapods.org/pods/SQLCipher). On ExpoUpdates, replace the dependency on sqlite3 with the same sqlcipher pod, maybe then cocoapods will be smart enough to only require it once. Once that is done, on the ExpoUpdate swift sources replace the import of sqlite3 with sqlcipher and it might work.

**Comment by vince-roy** [comment]
I believe it does build after taking the following steps in the [test repo](https://github.com/vince-roy/op-sqlcipher-android):
1. Delete: `./ios/Pods/Headers/Private/op-sqlcipher/sqlite3.h`
2. Delete `./ios/Pods/Headers/Public/op-sqlcipher/sqlite3.h`
3. Delete `./op-sqlcipher-android/node_modules/@op-engineering/op-sqlcipher/cpp/sqlite3.h`
4. in node_modules, find and replace import SQLite3 by import SQLCipher
5. Added: s.dependency 'SQLCipher', '~> 4.5' to: `node_modules/expo-updates/ios/EXUpdates.podspec`
6. ran npx pod-install again

**Comment by ospfranco** [comment]
Going to close this for now. Let me know if you face any more issues.

**Comment by vince-roy** [comment]
Thanks for the help @ospfranco. It is indeed resolved for us now!
