### ISSUE TITLE
iOS packaging error

### ISSUE THREAD

**Issue by hongyingyang78** [OP-Engineering/op-sqlcipher#9]
iOS works fine, but packaging error

<img width="542" alt="截屏2024-01-25 16 09 59" src="https://github.com/OP-Engineering/op-sqlcipher/assets/143774358/644e2af7-f931-4738-a109-18004e9cf29c">
<img width="743" alt="截屏2024-01-25 16 10 09" src="https://github.com/OP-Engineering/op-sqlcipher/assets/143774358/18fb9542-715d-4882-b785-d737559319ce">

**Comment by ospfranco** [comment]
Hard to say what might be the issue. You need to create a reproduction example.

**Comment by hongyingyang78** [comment]
1. New React native project
2. Add @op-engineering/op-sqlcipher
3. Create a table in App.js
4. iOS packaging

There is no problem with the operation, but the packaging error is reported. Is there any configuration I lack?
Below is the demo address and configuration screenshot I posted

https://github.com/hongyingyang78/TestDemo.git
<img width="762" alt="截屏2024-01-26 10 08 22" src="https://github.com/OP-Engineering/op-sqlcipher/assets/143774358/403662f6-7cf5-42e5-b011-7b2619fd14c5">

<img width="593" alt="截屏2024-01-26 10 09 35" src="https://github.com/OP-Engineering/op-sqlcipher/assets/143774358/1fa9164b-e89e-4ca5-a8cf-d68380830532">

<img width="1089" alt="截屏2024-01-26 10 09 50" src="https://github.com/OP-Engineering/op-sqlcipher/assets/143774358/fa80fe3e-f90b-4de0-bd01-13a817fe1831">



<img width="831" alt="截屏2024-01-26 10 09 57" src="https://github.com/OP-Engineering/op-sqlcipher/assets/143774358/938b7695-2866-4cc0-b574-1d1feae6deed">

**Comment by ospfranco** [comment]
This has to be a problem with your machine/environment. There are already people using the package without issues. Create a reproduction repo and I will try to build it in my machine.

**Comment by hongyingyang78** [comment]
You can download my code from this address    https://github.com/hongyingyang78/TestDemo.git

**Comment by ospfranco** [comment]
Just tried your project, indeed it fails to package but this has nothing to do with op-sqlcipher. The project seems incomplete or outdated. I created a new bare project from the CLI and packaging is working, also the example app.

I would suggest you update your CLI installation and generate a new project.

![Oscar Franco Screen 000912](https://github.com/OP-Engineering/op-sqlcipher/assets/1634213/390c4039-910f-434c-a50a-071d2e7ff65d)

**Comment by hongyingyang78** [comment]
@ospfranco     But I have no problem using your react-native-quick-sqlite to package. At the same time, I have several other local RN projects that integrate a lot of sdk packages without any problems. Only op-sqlcipher has a problem, and I don't think it's my problem

**Comment by hongyingyang78** [comment]
@ospfranco  The problem has been solved, it is not my problem, the problem appears in the podfile file, using op-sqlcipher can not use flipper, so this problem needs you to check the reason. Note: flipper_configuration => flipper_config line can solve the problem

**Comment by ospfranco** [comment]
Good to know! Glad you solved it. However flipper is deprecated and removed in the latest versions of RN. Even then, I tried it a new project with flipper and everything was working.
